In [110]:
import tensorflow as tf
tf.__version__

'2.0.0'

In [111]:
seq = tf.random.uniform((5, 4, 2))

In [112]:
gru = tf.keras.layers.GRU(16, return_sequences=True)

In [113]:
out = gru(seq)
out.shape

TensorShape([5, 4, 16])

In [114]:
t = tf.reshape(tf.range(0, 16), (2, -1))
t

<tf.Tensor: id=1322, shape=(2, 8), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]], dtype=int32)>

In [115]:
t[:,::2]

<tf.Tensor: id=1326, shape=(2, 4), dtype=int32, numpy=
array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14]], dtype=int32)>

In [116]:
out = tf.space_to_batch(t, [2], paddings=[[0, 0]])
out

<tf.Tensor: id=1329, shape=(4, 4), dtype=int32, numpy=
array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [ 1,  3,  5,  7],
       [ 9, 11, 13, 15]], dtype=int32)>

In [117]:
tf.batch_to_space(out, [2], crops=[[0, 0]])

<tf.Tensor: id=1332, shape=(2, 8), dtype=int32, numpy=
array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15]], dtype=int32)>

In [118]:
def drnn(rnn_size, skip):
    explode = tf.keras.layers.Lambda(lambda x: tf.space_to_batch(x, [2], paddings=[[0, 0]]))
    rnn = tf.keras.layers.GRU(rnn_size, return_sequences=True)
    implode = tf.keras.layers.Lambda(lambda x: tf.batch_to_space(x, [2], crops=[[0, 0]]))

    return lambda x: implode(rnn(explode(x)))

In [119]:
drnn(32, 2)(seq).shape

TensorShape([5, 4, 32])